hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	-- hl.exec_cmd("copyq --start-server")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("mako")
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar")
	hl.exec_cmd("clash-verge")
	hl.exec_cmd("~/.config/waybar/scripts/waybar-refresh.sh 999")
	hl.exec_cmd("~/.config/waybar/scripts/live-wallpaper-engine.sh")
	-- hl.exec_cmd("~/.config/hypr/clipboard-sync.sh")
	hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
end)
